<%
yum_dists_with_56 = %w(centos-6 centos-7 fedora-28 amazon-linux)
suse_dists_with_56 = %w(opensuse-leap)
apt_dists_with_56 = %w(ubuntu-14.04)
yum_dists_with_57 = %w(centos-6 centos-7 fedora-28 fedora-latest)
apt_dists_with_57 = %w(ubuntu-16.04 ubuntu-18.04)
%>
---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-28
  - name: opensuse-leap
    driver:
      box: bento/opensuse-leap-42
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux

suites:
  #
  # client
  #
  - name: installation_client_package-56
    run_list:
    - recipe[test::installation_client]
    attributes:
      mysql:
       version: '5.6'
    includes: <%= apt_dists_with_56 %>

  - name: installation_client_package-57
    run_list:
    - recipe[test::installation_client]
    attributes:
      mysql:
       version: '5.7'
    includes: <%= apt_dists_with_57 %>

  - name: installation_client_package-56-yum
    run_list:
    - recipe[selinux::disabled]
    - recipe[test::yum_repo]
    - recipe[test::installation_client]
    attributes:
      mysql:
       version: '5.6'
    includes: <%= yum_dists_with_56 %>

  - name: installation_client_package-56-suse
    run_list:
    - recipe[test::yum_repo]
    - recipe[test::installation_client]
    attributes:
      mysql:
       version: '5.6'
    includes: <%= suse_dists_with_56 %>

  - name: installation_client_package-57-yum
    run_list:
    - recipe[selinux::disabled]
    - recipe[test::yum_repo]
    - recipe[test::installation_client]
    attributes:
      mysql:
       version: '5.7'
    includes: <%= yum_dists_with_57 %>

  #
  # server smoke
  #

  - name: smoke56
    run_list:
      - recipe[test::smoke]
    attributes:
      mysql:
       version: '5.6'
    includes: <%= apt_dists_with_56 %>

  - name: smoke57
    run_list:
      - recipe[test::smoke]
    attributes:
      mysql:
       version: '5.7'
    includes: <%= apt_dists_with_57 %>

  - name: smoke56-yum
    run_list:
      - recipe[selinux::disabled]
      - recipe[test::yum_repo]
      - recipe[test::smoke]
    attributes:
      mysql:
       version: '5.6'
    includes: <%= yum_dists_with_56 %>

  - name: smoke56-suse
    run_list:
      - recipe[test::yum_repo]
      - recipe[test::smoke]
    attributes:
      mysql:
       version: '5.6'
    includes: <%= suse_dists_with_56 %>

  - name: smoke57-yum
    run_list:
      - recipe[selinux::disabled]
      - recipe[test::yum_repo]
      - recipe[test::smoke]
    attributes:
      mysql:
       version: '5.7'
    includes: <%= yum_dists_with_57 %>
